apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend 
  labels:
    app: {{ .Release.Name }}-backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: {{ .Values.backend.name }} 
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }} 
          ports:
            - containerPort: {{ .Values.backend.containerPort }} 
          env:
            - name: MONGO_URL
              value: "mongodb://{{ .Release.Name }}-mongo:27017/todo"
