apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }} 
  ports:
    - port: {{ .Values.frontend.service.port }}      
      targetPort: {{ .Values.frontend.service.targetPort }} 
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-frontend 