{{- if .Values.ingress.enabled }} 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress 
  labels:
    app: {{ .Release.Name }}-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }} # O host para o qual o Ingress responderá (k8s.local)
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-{{ .serviceName }} # Nome do Service para onde rotear (ex: meu-app-frontend)
                port:
                  number: {{ .servicePort }}                 
          {{- end }}
{{- end }}