apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: {{ .Release.Name }}-mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mongo.replicas }} 
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: {{ .Values.mongo.name }} 
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }} 
          ports:
            - containerPort: {{ .Values.mongo.containerPort }} 
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db            
      volumes:
        - name: mongo-persistent-storage
          {{- if .Values.mongo.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongo-pvc 
          {{- else }}
          emptyDir: {} 
          {{- end }}